version: "3.8"

services:
    nginx:
        depends_on:
            - api
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./frontend
        ports:
            - "3000:80"

    api:
        build:
            dockerfile: Dockerfile
            context: "./backend"
        volumes:
            - /app/node_modules
            - ./backend:/app
